name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{secrets.EMAIL_GITHUB}}
        git config --global user.name ${{secrets.UNAME_GITHUB}}
        git remote set-url origin https://${{secrets.PAT_GITHUB}}@github.com/${{secrets.UNAME_GITHUB}}/ReactGH.git
        npm run deploy